version: 2
formats: []
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz

python:
   install:
      - requirements: docs/requirements.txt
sphinx:
   builder: html
   configuration: docs/conf.py
